[workspace]
resolver = "3"
members = ["patmat", "configurator"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/ElectricPulse/patmat"
readme = "README.md"

[workspace.dependencies]
derive-where = "1.6.1"
drevo = { version = "0.1.6", git = "https://github.com/ElectricPulse/drevo" }
drevo-macros = { version = "0.1.3", git = "https://github.com/ElectricPulse/drevo" }

[workspace.lints.rust]
non_camel_case_types = "allow"
non_upper_case_globals = "allow"
unused_must_use = "warn"
unused_results = "warn"
