[workspace]
resolver = "3"
members = ["patmat", "configurator"]

[workspace.dependencies]
derive-where = "1.6.1"
vizual = { git = "https://github.com/ElectricPulse/vizual" }
vizual-macros = { git = "https://github.com/ElectricPulse/vizual" }

[workspace.lints.rust]
non_camel_case_types = "allow"
non_upper_case_globals = "allow"
unused_must_use = "warn"
unused_results = "warn"

[workspace.package]
readme = "README.md"
