[package]
name = "configurator"
version = "0.1.1"
edition.workspace = true
description = "A tree-based configuration editor for Patmat applications"
repository.workspace = true
license.workspace = true
categories = ["config", "gui"]
keywords = ["config", "editor", "tree", "gui", "vizual"]

[dependencies]
async-recursion = "1.1.1"
async-trait = "0.1.89"
color-eyre = "0.6.5"
derive-where.workspace = true
dyn-clone = "1.0.20"
indexmap = "2.13.0"
serde = "1.0.228"
serde-saphyr = "0.0.8"
tokio = "1.52.1"
uniqify = "0.1.0"
vizual.workspace = true
vizual-macros.workspace = true

[lints]
workspace = true
